[package]
edition = "2018"
name = "tuifw"
version = "0.0.8"
authors = ["warlock <internalmike@gmail.com>"]
description = "Text User Interface Framework."
readme = "README.md"
documentation = "https://docs.rs/tuifw-view/"
keywords = ["tui", "view", "layout", "property", "widget"]
categories = ["command-line-interface"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/A1-Triard/tuifw"

[workspace]
members = [
    "dep-obj",
    "screen-base",
    "screen-ncurses",
    "screen-winapi",
    "screen",
    "screen-test",
    "window",
]
exclude = [
    "ensure_no_std",
]

[dependencies]
components-arena = "2.1.5"
debug_panic = "0.2.1"
downcast-rs = { version = "1.2.0", default-features = false }
dyn-clone = "1.0.4"
dyn-context = "0.10.8"
dep-obj = { path = "dep-obj", version = "0.34.1" }
educe = "0.4.18"
either = { version = "1.6.1", default-features = false }
enum-derive-2018 = { version = "1.0.2", default-features = false }
errno = { git = "https://github.com/A1-Triard/rust-errno.git", default-features = false }
macro-attr-2018 = "1.1.1"
num-traits = { version = "0.2.14", default-features = false }
panicking = { version = "0.0.1", default-features = false }
tuifw-screen-base = { path = "screen-base", version = "0.10.0" }
tuifw-window = { path = "window", version = "0.10.0" }
unicode-segmentation = "1.8.0"
unicode-width = "0.1.8"

[dev-dependencies]
tuifw-screen = { path = "screen", version = "0.10.0" }
