[package]
edition = "2018"
name = "tuifw"
version = "0.0.5"
authors = ["warlock <internalmike@gmail.com>"]
description = "Text User Interface Framework."
readme = "README.md"
documentation = "https://docs.rs/tuifw-view/"
keywords = ["tui", "view", "layout", "property", "widget"]
categories = ["command-line-interface"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/A1-Triard/tuifw"

[workspace]
members = [
    "screen-base",
    "screen-ncurses",
    "screen-winapi",
    "screen",
    "screen-test",
    "window",
]

[dependencies]
components-arena = "2.1.5"
debug_panic = "0.2.1"
downcast-rs = "1.2.0"
dyn-clone = "1.0.4"
dyn-context = "0.10.5"
dep-obj = "0.25.0"
educe = "0.4.18"
either = "1.6.1"
enum-derive-2018 = "1.0.1"
macro-attr-2018 = "1.1.1"
panicking = "0.0.1"
tuifw-screen-base = { path = "screen-base", version = "0.8.1" }
tuifw-window = { path = "window", version = "0.8.1" }
unicode-segmentation = "1.7.1"
unicode-width = "0.1.8"

[dev-dependencies]
tuifw-screen = { path = "screen", version = "0.8.1" }
