[package]
edition = "2018"
name = "tuifw-screen"
version = "0.3.0"
authors = ["warlock <internalmike@gmail.com>"]
description = "Text User Interface Framework. Basic platform-independent text screen implementation."
readme = "README.md"
documentation = "https://docs.rs/tuifw-screen/"
keywords = ["tui", "screen"]
categories = ["command-line-interface"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/A1-Triard/tuifw"

[dependencies]
tuifw-screen-base = { path = "../screen-base", version = "0.3.0" }

[target.'cfg(not(windows))'.dependencies]
tuifw-screen-ncurses = { path = "../screen-ncurses", version = "0.3.0" }

[target.'cfg(windows)'.dependencies]
tuifw-screen-winapi = { path = "../screen-winapi", version = "0.3.0" }
