[package]
edition = "2021"
name = "ensure_no_std"
version = "0.0.1"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
dep-obj = "0.34.1"
dyn-context = "0.10.8"
libc_alloc = "1.0.3"
tuifw = { path = ".." }
tuifw-screen = { path = "../screen" }
winapi = { version = "0.3.9", features = ["processthreadsapi"] }
