[build.x86_64-pc-windows-msvc.dependencies]
alloc = { }
core = { }
std = { features = ["panic_unwind"] }

[target.x86_64-pc-windows-msvc.dependencies]
alloc = { }
core = { }

[build.x86_64-unknown-linux-gnu.dependencies]
alloc = { }
core = { }
std = { features = ["panic_unwind"] }

[target.x86_64-unknown-linux-gnu.dependencies]
alloc = { }
core = { }
