[package]
edition = "2018"
name = "tuifw-screen-base"
version = "0.4.1"
authors = ["warlock <internalmike@gmail.com>"]
description = "Text User Interface Framework. Basic platform-independent text screen interface."
readme = "README.md"
documentation = "https://docs.rs/tuifw-screen-base/"
keywords = ["tui", "ncurses", "notcurses", "screen"]
categories = ["command-line-interface", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/A1-Triard/tuifw"

[dependencies]
enum-derive-2018 = { version = "0.2.1", default-features = false }
macro-attr-2018 = "0.3.3"
bitflags = "1.2.1"
either = { version = "1.5.3", default-features = false }
num-traits = { version = "0.2.12", default-features = false }

[dev-dependencies]
quickcheck = "0.9.2"
quickcheck_macros = "0.9.1"
