[package]
edition = "2021"
name = "tuifw-window"
version = "0.12.0"
authors = ["warlock <internalmike@gmail.com>"]
description = "Text User Interface Framework. Overlappable hierachical windows."
readme = "README.md"
documentation = "https://docs.rs/tuifw-window/"
keywords = ["tui", "window"]
categories = ["command-line-interface"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/A1-Triard/tuifw"

[dependencies]
tuifw-screen-base = { path = "../screen-base", version = "0.12.0" }
components-arena = "3.0.1"
dyn-context = "0.17.2"
educe = "0.4.18"
errno-no-std = { version = "0.1.0", default-features = false }
macro-attr-2018 = "2.1.0"

[dev-dependencies]
tuifw-screen-test = { path = "../screen-test", version = "0.12.0" }
tuifw-screen = { path = "../screen", version = "0.12.0" }

[badges]
maintenance = { status = "experimental" }
