[package]
edition = "2018"
name = "tuifw-window"
version = "0.8.1"
authors = ["warlock <internalmike@gmail.com>"]
description = "Text User Interface Framework. Overlappable hierachical windows."
readme = "README.md"
documentation = "https://docs.rs/tuifw-window/"
keywords = ["tui", "window"]
categories = ["command-line-interface"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/A1-Triard/tuifw"

[dependencies]
tuifw-screen-base = { path = "../screen-base", version = "0.8.1" }
components-arena = "1.2.0"
educe = "0.4.18"
macro-attr-2018 = "1.1.0"
dyn-context = "0.6.0"

[dev-dependencies]
tuifw-screen-test = { path = "../screen-test", version = "0.8.1" }
tuifw-screen = { path = "../screen", version = "0.8.1" }
