[package]
edition = "2018"
name = "dep-obj"
version = "0.0.19"
authors = ["warlock <internalmike@gmail.com>"]
description = "Dependency object: effective reactive heterogeneous container."
readme = "README.md"
documentation = "https://docs.rs/dep-obj/"
keywords = ["property", "reactive", "dependency", "runtime", "type"]
categories = ["rust-patterns", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/A1-Triard/dep-obj"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
educe = "0.4.13"
components-arena = { version = "0.8.5", default-features = false }
dyn-context = { version = "0.0.5", default-features = false }
paste = "1.0.0"

[dev-dependencies]
macro-attr-2018 = "0.3.3"
downcast-rs = { version = "1.2.0", default-features = false }
