[package]
edition = "2018"
name = "dep-obj"
version = "0.0.28"
authors = ["warlock <internalmike@gmail.com>"]
description = "Dependency object: effective reactive heterogeneous container."
readme = "README.md"
documentation = "https://docs.rs/dep-obj/"
keywords = ["property", "reactive", "dependency", "runtime", "type"]
categories = ["rust-patterns", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/A1-Triard/dep-obj"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
educe = "0.4.13"
components-arena = { version = "1.0.1", default-features = false }
dyn-context = { version = "0.3.0", default-features = false }
paste = "1.0.0"
dyn-clone = "1.0.2"
generics = "0.1.2"
memoffset = { version = "0.5.5", features = ["unstable_const", "unstable_raw"] }

[dev-dependencies]
macro-attr-2018 = "1.0.0"
downcast-rs = { version = "1.2.0", default-features = false }
