[package]
edition = "2018"
name = "dep-obj"
version = "0.0.5"
authors = ["warlock <internalmike@gmail.com>"]
description = "Dependency object: effective reactive heterogeneous container."
readme = "README.md"
documentation = "https://docs.rs/dep-obj/"
keywords = ["property", "reactive", "dependency", "runtime", "type"]
categories = ["rust-patterns", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/A1-Triard/dep-obj"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
derivative = "2.1.1"
components-arena = { version = "0.6.1", default-features = false }

[dev-dependencies]
macro-attr = "0.2.0"
downcast = "0.10.0"
once_cell = "1.4.0"
