name: CI 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: '0 0 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
          triple: x86_64-unknown-linux-gnu
          features: ""
        - os: ubuntu-latest
          triple: x86_64-unknown-linux-gnu
          features: "--features=serde"
        - os: windows-latest
          triple: x86_64-pc-windows-msvc
          features: ""
        - os: windows-latest
          triple: x86_64-pc-windows-msvc
          features: "--features=serde"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - run: "rustup component add clippy"
    - run: "curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash"
      if: ${{ matrix.os == 'ubuntu-latest' }}
    - run: "cargo binstall cargo-outdated"
      if: ${{ matrix.os == 'ubuntu-latest' }}
    - run: "rustup component add rust-src --toolchain nightly-${{ matrix.triple }}"
    - uses: actions/checkout@v2
    - run: "cargo build --verbose --no-default-features ${{ matrix.features }}"
    - run: "cargo test --verbose --tests --no-default-features ${{ matrix.features }}"
    - run: "cargo test --verbose --doc --no-default-features ${{ matrix.features }}"
    - run: "cargo doc --verbose --no-default-features ${{ matrix.features }}"
    - run: "cargo build --verbose --release --no-default-features ${{ matrix.features }}"
    - name: remove Cargo.lock
      uses: JesseTG/rm@v1.0.3
      with:
        path: Cargo.lock
    - run: "cargo outdated --verbose --root-deps-only --exit-code 1 ${{ matrix.features }}"
    - run: "cargo clippy --verbose --no-default-features ${{ matrix.features }}"
    - run: "cargo +nightly build --verbose -Z build-std=core,panic_abort --target ${{ matrix.triple }} --release"
      working-directory: ensure_no_std
    - run: "./ensure_no_std/target/${{ matrix.triple }}/release/ensure_no_std"
