name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [nightly]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    - name: install rust-src
      run: "rustup component add rust-src"
    - name: install xargo
      run: "cargo install --verbose xargo"
    - name: build
      run: "cargo build --verbose --workspace"
    - name: test --tests
      run: "cargo test --verbose --workspace --tests"
    - name: test --doc
      run: "cargo test --verbose --workspace --doc"
    - name: doc
      run: "cargo doc --verbose --workspace"
    - name: build --release
      run: "cargo build --verbose --workspace --release"
    - name: ensure_no_std clean
      working-directory: "ensure_no_std"
      run: "xargo clean --verbose"
    - name: ensure_no_std build
      working-directory: "ensure_no_std"
      run: "xargo build --verbose --target x86_64-unknown-linux-gnu"
    - name: ensure_no_std run
      working-directory: "ensure_no_std"
      run: "xargo run --verbose --target x86_64-unknown-linux-gnu"
