name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [nightly]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    - name: build
      run: "cargo build --verbose --workspace"
    - name: test --tests
      run: "cargo test --verbose --workspace --tests"
    - name: test --doc
      run: "cargo test --verbose --workspace --doc"
    - name: doc
      run: "cargo doc --verbose --workspace"
    - name: build --release
      run: "cargo build --verbose --workspace --release"
    - name: ensure_no_std build
      working-directory: "ensure_no_std"
      run: "cargo build --verbose"
    - name: ensure_no_std run
      working-directory: "ensure_no_std"
      run: "cargo run --verbose"
