[package]
edition = "2018"
name = "tuifw-screen-winapi"
version = "0.10.0"
authors = ["warlock <internalmike@gmail.com>"]
description = "Text User Interface Framework. Basic text screen implementation for Win platform."
readme = "README.md"
documentation = "https://docs.rs/tuifw-screen-winapi/"
keywords = ["tui", "winapi", "screen"]
categories = ["command-line-interface"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/A1-Triard/tuifw"

[dependencies]
tuifw-screen-base = { path = "../screen-base", version = "0.10.0" }
unicode-segmentation = "1.8.0"
either = { version = "1.6.1", default-features = false }
num-traits = { version = "0.2.14", default-features = false }
panicking = { version = "0.0.1", default-features = false }
winapi = { version = "0.3.9", features = [
    "consoleapi",
    "errhandlingapi",
    "handleapi",
    "impl-default",
    "processenv",
    "stringapiset",
    "winbase",
    "wincon",
    "wincontypes",
    "winnls",
    "winuser"
] }
